// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASV8QUSrrsdQC2BCxHpX4EDY3YhBZwmWM',
    appId: '1:1068295308927:web:3126ff58c3ff4e0e8d214a',
    messagingSenderId: '1068295308927',
    projectId: 'chat2025-eae81',
    authDomain: 'chat2025-eae81.firebaseapp.com',
    storageBucket: 'chat2025-eae81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-EkeE-GnQl1jJ7RwyjOe2e1hgAR_jS30',
    appId: '1:1068295308927:android:990b4e3bfbe9f7038d214a',
    messagingSenderId: '1068295308927',
    projectId: 'chat2025-eae81',
    storageBucket: 'chat2025-eae81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW0YNkLtDp9tS6qi7dRP9auUX9Irg1q8k',
    appId: '1:1068295308927:ios:f59e340dc1b671da8d214a',
    messagingSenderId: '1068295308927',
    projectId: 'chat2025-eae81',
    storageBucket: 'chat2025-eae81.firebasestorage.app',
    iosBundleId: 'com.example.chat2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW0YNkLtDp9tS6qi7dRP9auUX9Irg1q8k',
    appId: '1:1068295308927:ios:f59e340dc1b671da8d214a',
    messagingSenderId: '1068295308927',
    projectId: 'chat2025-eae81',
    storageBucket: 'chat2025-eae81.firebasestorage.app',
    iosBundleId: 'com.example.chat2025',
  );

}